evilsoft/crocks

README.md, crocks/List.js, crocks/List.spec.js, funcs/ifElse.js, funcs/ifElse.spec.js, funcs/safe.js, funcs/safe.spec.js, funcs/unless.js, funcs/unless.spec.js, funcs/when.js, funcs/when.spec.js, pointfree/filter.js, pointfree/filter.spec.js
Well now that we have dat handy dandy `Pred` I guess we should put it to work. Updated the following predicate based functions to accept and run a given `Pred`:
* `filter` & `List.filter`
* `ifElse`
* `safe`
* `unless`
* `when`
=> Allow for Pred to be used with safe, ifElse, unless, when and filter

README.md, crocks/Arrow.js, crocks/Const.js, crocks/Either.js, crocks/IO.js, crocks/Identity.js, crocks/List.js, crocks/Maybe.js, crocks/Pair.js, crocks/Pred.js, crocks/Reader.js, crocks/Star.js, crocks/State.js, crocks/Unit.js, crocks/Writer.js, internal/inspect.js, internal/inspect.spec.js, monoids/All.js, monoids/Any.js, monoids/Assign.js, monoids/Max.js, monoids/Min.js, monoids/Prod.js, monoids/Sum.js, test/LastMonoid.js
This PR is the last required portion to address [issue#17](https://github.com/evilsoft/crocks/issues/17). 
As `inspect` is no longer available on the Public API, seems odd to keep it inside of `helpers`. This PR moves it to the `internal` folder in the project.
=> Move inspect into internal from helpers

README.md, pointfree/sequence.js, pointfree/sequence.spec.js, pointfree/traverse.js, pointfree/traverse.spec.js
This PR addresses [issue#1](https://github.com/evilsoft/crocks/issues/1).
It allows both the `sequence` and `traverse` point-free functions to work on Arrays.
=> Allow `traverse` and `sequence` to accept arrays

.jshintignore, .jshintrc, .npmignore, .travis.yml, README.md, crocks/Unit.js, helpers/once.js, package.json
This PR addresses [Issue#22](https://github.com/evilsoft/crocks/issues/22).
* Adds Travis integration to repo
* updates `.npmignore` to keep dev config out of npm package
* Sets up `jshint` for dat `crocks` style (need to set up a style guide for contributors)
* Adds the Travis badge to the README
* :wrench:  some of the npm scripts to work with the linting addition.
* :wrench: some linting errors that came back :taco: :tada:
=> Add JSHint and Hook up Travis

.gitignore, .npmignore, .travis.yml, README.md, package.json
This PR addresses [issue#35](https://github.com/evilsoft/crocks/issues/35) and gets coveralls added in there complete with a cutesy badge of scary (spice).
=> Add and configure coveralls for code coverage reporing

.gitignore, .npmignore, README.md, crocks.js, crocks.spec.js, crocks/Arrow.js, crocks/Arrow.spec.js, crocks/Async.js, crocks/Star.js, crocks/Star.spec.js, helpers/safeLift.js, package.json, pointfree/both.js, pointfree/both.spec.js, pointfree/first.js, pointfree/second.spec.js
This PR addresses [issue#36](https://github.com/evilsoft/crocks/issues/36) and does the following:
* Add a `both` point-free function that accepts: `Arrow`, `Function` or `Star`.
* Add `both` to `Arrow`
* Add `both` to `Star`
In addition to that did a little 💄 on a few things I noticed:
* Fix up coverage to set limits to 100% (:100:)
* Exclude stuffs I do not care about from coverage reporting
* Updated the siggy for `safeLift`.
* Remove needless `null` defaulting for context argument to `Async.fromNode`
* Fix up type checking for both `first` and `second` pointfree functions.
=> Add `both` to `Arrow` and `Star` with an additional pointfree function

README.md, crocks.js, crocks.spec.js, package.json, transforms/eitherToAsync.js, transforms/eitherToAsync.spec.js, transforms/eitherToMaybe.js, transforms/eitherToMaybe.spec.js, transforms/maybeToAsync.js, transforms/maybeToAsync.spec.js, transforms/maybeToEither.js, transforms/maybeToEither.spec.js
This PR addresses [issue#47](https://github.com/evilsoft/crocks/issues/47) and adds all the initial natural transofrmation functions. Really only covers the two main Sum Types `Maybe` and `Either` back and forth and to `Async`. Once `Validation` is added, will add an additional set of functions to account for those transformations.
=> Add Inital Transformation Functions

crocks/Async.js, crocks/Either.js, crocks/IO.js, crocks/IO.spec.js, crocks/Identity.js, crocks/Maybe.js, crocks/Pair.js, crocks/Reader.js, crocks/Reader.spec.js, crocks/Writer.js, pointfree/concat.js, pointfree/either.js
This PR addresses [issue#49](https://github.com/evilsoft/crocks/issues/49)
Seems I was as Lazy as some of my earlier Lazy types. I failed to add Error handling for `chain` on both `IO` and `Reader`. I never checked if the value returned by the function was indeed the same type, so any errors were happening when run, with no indication of what the heck happened. 
This PR fixes that.
Also noticed some in:corn:sistancies with some of the error messages not being Capitalized. :wrench: that too!!
=> :corn:sistant errors and add chain errors to IO and Reader

docs/crocks/Either.md
Does not conform to other spec library variables [Either l r].  I feel it is easier to follow, but I _might_ be wrong [because !:corn:sistency]
=> Adds Either API to docs

README.md, crocks/Either.js, crocks/Either.spec.js, crocks/Maybe.js, crocks/Maybe.spec.js
This PR addresses [issue#54](https://github.com/evilsoft/crocks/issues/54) and removes `value` from `Either` and `maybe` from `Maybe`. 
These functions were wrought with nasty and would have been a big 👃 if allowed to hang out.
Also did some 💅 on the README fixing up some text and updating the pointfree example to lean on techniques that were added in the last few releases.
=> Remove extraction functions from `Either` and `Maybe`

crocks/List.js, crocks/List.spec.js
#61 
Right now we require an Array to be passed into List and this becomes silly when trying to use List as a Monoid in this fra... 😴
=> List: Adds constructor _fromArray_ and instance _toArray_

README.md, crocks.js, crocks.spec.js, crocks/Async.js, crocks/Async.spec.js, crocks/Either.js, crocks/Either.spec.js, crocks/Maybe.js, crocks/Maybe.spec.js, pointfree/alt.js, pointfree/alt.spec.js, pointfree/ap.js, predicates/isAlt.js, predicates/isAlt.spec.js
This PR adds `alt` to instance of the following:
* `Async`
* `Either`
* `Maybe`
`alt` pointfree and `isAlt` predicates functions were also added. Not going to add `isPlus` right now because I am deciding how to deal with JS types that can be falsey.
Also adds `zero` to both the instance and constructor of `Maybe`
=> Add `alt` and `zero` for `Alt` and `Plus` on the Coproducts

README.md, crocks/Async.js, crocks/Async.spec.js, transforms/eitherToAsync.js, transforms/maybeToAsync.js
It was really bugging me that we went with `rejected` and `of` on `Async`.
This PR 🔧 that and adds `Resolved` and `Rejected` to the `Async` constructor.
=> Make Async more :corn:sistant with Resovled/Rejected

crocks/List.js, crocks/List.spec.js
This PR addresses the first item on this [issue](https://github.com/evilsoft/crocks/issues/61).
It allows the `List` constructor to do one of two things. If it receives in `Array` it will `slice` it and use that as the wrapped value. But if it receives any other value, it will lift that value into an `Array` for use internally.
It will still throw if it receives no input.
=> Update List constructor to act like `of` for non-array values

crocks/List.js, helpers/safe.js, internal/predOrFunc.js, internal/predOrFunc.spec.js, logic/and.js, logic/ifElse.js, logic/not.js, logic/or.js, logic/unless.js, logic/when.js, pointfree/filter.js, pointfree/filter.spec.js, pointfree/reject.js
Well time to DRY some bits up, we are at that stage now as many of the abstractions are presenting themselves. The simplest and most obvious is the selection of either a predicate function or running a `Pred`. This is the first of many clean up PRs that will be coming down the pipe as we get close to `1.0.0`
All this does is replace the copied selection code with a new helper that captures that flow.
=> Clean up Logic functions with new `predOrFunc` internal helper

README.md, crocks/Either.js, crocks/Either.spec.js, crocks/Identity.js, crocks/Identity.spec.js, crocks/Maybe.js, crocks/Maybe.spec.js, internal/innerConcat.js, internal/innerConcat.spec.js, predicates/isSameType.js, predicates/isSameType.spec.js
This PR was requested by an early tester of things. It adds `concat` to the simple value types and will concat inner values if they contain `Semigroups` of the same type.
Also there is a BIG ol breaking change: I updated `isSameType` to be able to compare native JS types, not just the `crocks` types. So things like this can be done:
* `isSameType(String, 'hello') // true`
* `isSameType('goodbye', 'hello') // true`
* `isSameType('goodbye', Array) // false`
* `isSameType([ 'a' ], 'a') // false`
=> Add `concat` to `Maybe`, `Either` and `Identity`

README.md, crocks/Arrow.js, crocks/Arrow.spec.js, crocks/Pair.js, crocks/Pair.spec.js, crocks/Star.js, crocks/Star.spec.js, helpers/branch.spec.js
This PR addresses [issue#59](https://github.com/evilsoft/crocks/issues/59).
`of` and `value` are proving to be problematic and create more issues then solve. This removes them and switches over all dependent specs to use `merge` for extraction.
=> Remove of and value from Pair

crocks/Pred.js, crocks/Pred.spec.js
Looks like we were not returning `Boolean` values from runWith in `Pred`, we should.
This PR fixes that.
=> `Pred` should only return `Boolean`s

docs/crocks/Either.md, docs/crocks/Identity.md, docs/crocks/Maybe.md, docs/crocks/Pair.md
This updates the docs to match the upcoming/already released `0.4.0`
This tracks: 
* Removal of `of` and `value` from `Pair`.
* Addition of `concat` to `Identity`, `Either` and `Maybe`
=> Update docs to match 0.4.0 release

docs/crocks/Async.md, docs/crocks/Either.md, docs/crocks/Maybe.md, docs/crocks/Pair.md
This PR addresses a portion of [issue#42](https://github.com/evilsoft/crocks/issues/42), namely adding the skeleton for the `Async` crock. As a super duper bonus, fixed up some of the other binary functions on `Either`, `Maybe` and `Pair` to represent their "uncurried" interface when on the `crock` itself.
=> Add the `Async` Skeleton.

docs/crocks/Unit.md
This PR addresses a portion of [issue#42](https://github.com/evilsoft/crocks/issues/42), namely adding the skeleton for the `Unit` crock. Was going to remove it, but I like how it fits in with `State` gonna be a keeper.
=> Add the `Unit` Skeleton

docs/crocks/State.md
This PR adds another skeleton to the docs for this [issue#42](https://github.com/evilsoft/crocks/issues/42). This one for the `State`. 
Nothing fancy here. Gonna try out an abbreviated format like the one introduced here on [`Star`](https://github.com/evilsoft/crocks/pull/98)
=> Add State Skeleton

docs/crocks/Arrow.md, docs/crocks/Star.md
This PR adds another skeleton to the docs for this [issue#42](https://github.com/evilsoft/crocks/issues/42). This one for the `Star`. Also in anticipation of the removal of the monoidial implementation on `Arrow` (broken in sooo many ways), this PR also removes the `concat`, `empty` and `value` bits off of `Arrow`
=> Add Star skeleton

README.md, helpers/tryCatch.js, helpers/tryCatch.spec.js
Now that we have the `Result` type, it makes a lot more sense to have the `tryCatch` helper return this new type and not an `Either`.
=> `tryCatch` should return a `Result` and not an `Either`

crocks/Either.js, crocks/Either.spec.js, crocks/Maybe.js, crocks/Maybe.spec.js, crocks/Result.js, crocks/Result.spec.js
Found that prefixing the type was so gross in practice. After seeing something that @joneshf did with his `toString` function on his Trees read sooo much better. So we gonna drop dat type from the inspect string. So instead of `Maybe.Just 23`, only going to show `Just 23`
=> Remove parent type on inspect string for sum types

README.md, internal/array.js, internal/object.js, internal/object.spec.js, pointfree/filter.js, pointfree/filter.spec.js, pointfree/reject.js, pointfree/reject.spec.js
This PR address [issue#117](https://github.com/evilsoft/crocks/issues/117).
* Adds a type rep for `Object` in the internal folder to implement a common `filter`.
* Update point-free `filter` to work with `Object` values.
* Update point-free `reject` to work with `Object` values.
* fix up some existing specs for both `filter` and `reject`
=> Update `reject` and `filter` to accept Objects

helpers/compose.js, helpers/compose.spec.js, helpers/composeP.js, helpers/composeP.spec.js, helpers/pipe.js, helpers/pipe.spec.js, helpers/pipeP.js, helpers/pipeP.spec.js
The initial implementation of one of the most commonly used functions made me...well...a little :sob:. We were traversing the list of functions twice, once for validation and another time to build the composition. On top of that, if people use `compose` (the more popular of these functions) we actually went through it (3) times. 
While there is a little duplication, that may turn out to be okay as we trudge onto a mono-repo. So I am okay with it here. (I guess). In addition to these flow changes, I also updated the specs to look for specific errors instead of the `TypeError` blanket for `pipe` and `compose`
=> Better compose and pipe functions

.npmignore, bin/publish, index.js, package.json
This is the penultimate PR for the new API change. This will get us yet another step to a well needed mono-repo. All this does is add a simple script that copies over the non-built assets needed for publish and ONLY publishes the compiled code directory allowing for references like:
```js
const Maybe = require('crocks/Maybe')
const safe = require('crocks/Maybe/safe')
// also can just:
const { Maybe, safe } = require('crocks')
```
The FINAL step before `0.7.0` is to allow for Type Proxies to remove dependencies for simple type checks. This will allow, say, functions that depend on a `Pair` but do not construct a `Pair` exists without needing to bring in `Pair`. Removing unneeded inner-dependencies.
=> Add publish bits for new api

src/Reader/Reader.spec.js, src/Reader/index.js, src/State/State.spec.js, src/State/index.js, src/core/List.js, src/core/Maybe.js, src/core/Pair.js, src/core/Unit.js
A common pattern when using `Reader.get` is to do something like `Reader.get(identity)` when one wants to use the environment as is, with no additional mapping. Because of this, it makes sense to allow for a version of the function that will automatically map identity when no arguments are passed.
As `State` provides a similar function with `State.get`, it makes sense to have that function follow suit. So now, with this PR both `Reader.ask` and `State.get` will map identity when nothing is passed to the function. If a function is in fact passed to those functions, then they will behave as normal, mapping the function over the environment or state.
=> Make `Reader.ask` and `State.get` use identity by default

src/Star/Star.spec.js, src/Star/index.js, src/helpers/fanout.js, src/helpers/fanout.spec.js, test/MockCrock.js
This is a breaking change on `Star` that now requires a `Monad` constructor to get back the actual constructor to use.
```js
const MaybeStar = Star(Maybe)
// isValid : a -> Maybe a
const isValid = 
safe(isNumber)
const m = 
MaybeStar(isValid)
.map(add(10))
.map(multiply(2))
m.runWith(5)   // Just 30
m.runWith('a') // Nothing
// now with `id`
const left =
MaybeStar.id().compose(m)
const right =
m.compose(MaybeStar.id())
left.runWith(10)  // Just 40
right.runWith(10) // Just 40
```
Doing this allows for implementation of `id` making this `Star` a `Category`.
=> Make `Star` a `Category` by fixing it to a given `Monad`

src/Result/Result.spec.js, src/Result/index.js
After messing about with `Alt` and trying to come up with helpers for `Alternative` and `Alt`, I was really sad that `Result` did not accumulate `Err` like it does with `ap`. It would be very useful and does not ***seem*** to break any laws.
So that is what this is. Now if you use a `Semigroup` for your `Err` and use `alt` it will concat your Errs. If you do not use a `Semigroup`, then `alt` behaves in a manner that works like `Either.alt`, in which it return the first `Ok`, but the last `Err`. Like so:
```js
const withSemi =
Err([ 3 ])
.alt(Err([ 13 ]))
.alt(Err([ 42 ]))
const noSemi =
Err(3)
.alt(Err(13))
.alt(Err(42))
withSemi
// > Err [ 3, 13, 42 ]
withSemi
.alt(Ok('yep'))
// > Ok 'yep'
noSemi
// > Err 42
noSemi
.alt(Ok('yep'))
// > Ok 'yep'
```
=> Accumulate `Err` on `Alt` for `Result` type

README.md, src/Pair/writerToPair.js, src/Pair/writerToPair.spec.js, src/core/Pair.js, src/core/Pair.spec.js, src/index.js, src/index.spec.js
This PR adds a couple ways to transform around the `Pair` type:
* adds `writerToPair` as a standard transformation function
* adds a `toArray` method to the `Pair` instance, that will...well...return an `Array` from a given `Pair`.
No big whoop!
=> Add Some Pair Transforms

src/All/README.md, src/Any/README.md, src/Arrow/Arrow.spec.js, src/Arrow/README.md, src/Arrow/index.js
These are the first in a series of Readmes to be added. This is another step in the [Quest for monorepo](https://github.com/evilsoft/crocks/issues/116).
Both `All` and `Any` did not require any API changes, while there was no need to keep `value` for `Arrow` as it no longer is used as a "traditional" `Monoid` as it was before `Category` was a thing.
This is a BREAKING API change. No depreciation, just dropping it.
=> Add READMEs for All, Any and Arrow types

README.md, src/Pair/writerToPair.js, src/Writer/Writer.spec.js, src/Writer/index.js
I really hate the lack of usability with the `Writer`'s `read` function. I also not like how it removed the Monoid from the `log` value. This PR now returns a `Pair` for `w.read()` with the Monoid wrapped `log` in the `fst` and the `value` in the `snd`.
With this change we now get the power of a `Pair` when we are done with the writing. Also it makes more sense as `Pair` is the canonical Product type.
This is a BREAKING change, will not depreciate, just changing straight away.
=> Return `Pair` for `Writer`'s `read` method

README.md
Small update to the readme.
The `branch` function is accessed through `crocks/Pair/branch`
=> Updated path for branch - helpers -> Pair

src/State/State.spec.js, src/State/index.js
On `State` the `runWith` method did not throw if one did not return a `Pair`. This PR now does that and uses this new error to clean up some more of the error handling for all the methods.
Thinking this is more a Bug Fix then a Breaking change...But we will see hows I Feelz when the release actually goes out.
=> Better `runWith` errors for State

src/Pred/README.md
This PR just adds some documentation around the `Pred` datatype in response to [this issue](https://github.com/evilsoft/crocks/issues/42)
=> Add Documentation for the `Pred` datatype

README.md, docs/src/pages/docs/functions/combinators.md, docs/src/pages/docs/functions/helpers.md, docs/src/pages/docs/functions/index.md, docs/src/pages/docs/functions/logic-functions.md
The functions were a bit difficult to navigate in the docs. This PR lays the ground work for how functions and other bits should be xref. It is very (e)manual (lewis), but it is a start. Once we get the pattern down, we can see about using something like `markdown-toc` or use some build state to track links. But it all starts with the horrible, tedious manual process.
=> Index and Cross Reference Function Documentation

docs/src/pages/docs/functions/pointfree-functions.md
There were some casing issues that were missed in the original implementation of the pointfree links. Thinking about moving the docs system into Docker if this becomes a problem for those times we do docs work in a case-preserving, case-insensitive filesystem like HFS.
=> Correct casing for Point-free links in Docs

.all-contributorsrc, .eslintignore, .travis.yml, AUTHORS, CONTRIBUTORS.md, README.md, bin/publish, docs/src/pages/docs/getting-started.md, docs/src/pages/index.soy, package-lock.json, package.json
This is another push to make the lib a little less frightening and give credit where credit is due.
Now that we have these docs in play, no need for that horrible, hard to navigate README. And now that the README is cleaned up, we have space for showing what matters most, the people working to make this project a thing.
So this PRs main focus is to implement all-collaborators and provide credit in the npm module for the people who have subbmitted code. All in all this is what this does:
* Add `all-collaborators` and two scripts to manage that. 
* Remove all the documentation from the README and only show usage and install.
* Add a Collaborators section with the output of `all-collaborators`.
* Add a TOC to the main README (and a script for executing it).
* Remove the ignore for the main …
=> Clean up Docs/Readme and Implement all-collaborators 

docs/package-lock.json, docs/package.json, docs/src/pages/docs/crocks/Arrow.md, docs/src/pages/docs/crocks/Equiv.md, docs/src/pages/docs/crocks/Pred.md, docs/src/pages/docs/crocks/Reader.md, docs/src/pages/docs/crocks/ReaderT.md, docs/src/pages/docs/crocks/State.md, docs/src/pages/docs/crocks/index.md, docs/src/pages/docs/functions/pointfree-functions.md, docs/src/pages/docs/monoids/All.md, docs/src/pages/docs/monoids/Any.md, docs/src/pages/docs/monoids/Assign.md, docs/src/pages/docs/monoids/Prod.md, docs/src/pages/docs/monoids/Sum.md, docs/src/pages/docs/monoids/index.md, src/All/README.md, src/Any/README.md, src/Arrow/README.md, src/Equiv/README.md, src/Pred/README.md, src/Reader/README.md, src/State/README.md
This PR does a sweep through the docs for some cleanup and to unify some of the "patterns" for representing docs in this lib. Mostly makes it easier to keep up with documentation.
This PR does the following:
- Remove needless `markdown-toc` dep in docs folder.
- Remove headings on Monoids and Crocks index pages
- Add lib paths to State's pointfree functions.
- Add proper spacing between "blocks"/sections in the existing READMEs
- Use `javascript` for all code blocks, no more `js`.
- Add the following `Monoid`s to the pretty docs:
- `Assign`
- `Prod`
- `Sum`
=> More Documentation Cleanup

bin/setup, package.json, src/Either/Either.spec.js, src/Either/index.js, src/Identity/Identity.spec.js, src/Identity/index.js, src/Result/Result.spec.js, src/Result/index.js, src/core/List.js, src/core/List.spec.js, src/core/Maybe.js, src/core/Maybe.spec.js, src/core/array.js, src/core/array.spec.js
Noticed that we were not accepting `Array` for traversable types while it was a valid Applicative. This PR addresses [this issue](https://github.com/evilsoft/crocks/issues/181) and allows for `Array`s as the Applicative for the following types:
* `Array`
* `Either`
* `Identity`
* `List`
* `Maybe`
* `Result`
=> Accept Array as the Applicative for Traversable Types

docs/src/pages/docs/monoids/All.md, docs/src/pages/docs/monoids/Any.md, src/All/README.md, src/Any/README.md, src/Arrow/README.md, src/Assign/README.md, src/Equiv/README.md, src/Pred/README.md, src/Prod/README.md, src/Reader/README.md, src/State/README.md, src/Sum/README.md
This PR cleans up the section headings to make it easier to keep the READMEs in sync with the documentation on dem git pages. Need to get :corn:sistant with how these docs should be styled as more people want to contribute time on the docs.
=> Clean up heading on existing READMEs

src/Endo/README.md
This PR addresses adding the `Endo` documentation from [this issue](https://github.com/evilsoft/crocks/issues/42). Once this PR is merged, will do a follow up PR to move this over to the git pages documentation.
=> Add Documentation for `Endo`

docs/src/pages/docs/crocks/Arrow.md, docs/src/pages/docs/crocks/Equiv.md, docs/src/pages/docs/crocks/Maybe.md, docs/src/pages/docs/crocks/Pred.md, docs/src/pages/docs/crocks/Reader.md, docs/src/pages/docs/crocks/State.md, docs/src/pages/docs/crocks/index.md, docs/src/pages/docs/monoids/All.md, docs/src/pages/docs/monoids/Any.md, docs/src/pages/docs/monoids/Assign.md, docs/src/pages/docs/monoids/Endo.md, docs/src/pages/docs/monoids/Prod.md, docs/src/pages/docs/monoids/Sum.md, docs/src/pages/docs/monoids/index.md, src/All/README.md, src/Any/README.md, src/Arrow/README.md, src/Assign/README.md, src/Endo/README.md, src/Equiv/README.md, src/Maybe/README.md, src/Pred/README.md, src/Prod/README.md, src/Reader/README.md, src/State/README.md, src/Sum/README.md
With the `isSameType` function being added a while ago, there is not much use for `type` to really be used. So there is going to be the first in a three step transition to move to the more well know `@@type` method and format (lib/type/version).
To keep newcomers from even know about this, the first step to not talk about. Followed by the implementation and hooks for `@@type`. Then the completle and breaking removal of `type` from the ADTs.
=> Remove mention of the type method from Documentation

src/First/README.md
This PR addresses another item on [this issue]() and adds the README for the `First` Monoid. Before the next release (2) other READMEs will be added, one for `Async` and another for `Last`. Once all (3) are merged, we will move them over to the overall docs.
=> Add `First` documentation

src/First/README.md, src/Last/README.md
This is another PR that addresses the `Last` item on [this issue](https://github.com/evilsoft/crocks/issues/42) by adding the README for the `Last` monoid. It is pretty much the same thing as `First`, but kinda the opposite.
Also made some corrections to the `First` README in this PR as well.
=> Add `Last` Documentation

docs/src/pages/docs/functions/pointfree-functions.md, docs/src/pages/docs/functions/transformation-functions.md, docs/src/pages/docs/monoids/First.md, docs/src/pages/docs/monoids/Last.md, docs/src/pages/docs/monoids/index.md, package.json
This PR add both the `Last` and `First` monoids to the main documentation and takes care of all the links to other portions of the docs. Also as a side note, adds the documentation url for the homepage in the `package.json`
=> Add First and Last monoids to documentation

src/All/index.js, src/Any/index.js, src/Arrow/index.js, src/Assign/index.js, src/Async/index.js, src/Const/index.js, src/Either/index.js, src/Endo/index.js, src/Equiv/index.js, src/First/index.js, src/IO/index.js, src/Identity/index.js, src/Last/index.js, src/Max/index.js, src/Min/index.js, src/Pred/index.js, src/Prod/index.js, src/Reader/ReaderT.js, src/Reader/index.js, src/Result/index.js, src/Star/index.js, src/State/index.js, src/Sum/index.js, src/Writer/index.js, src/core/List.js, src/core/Maybe.js, src/core/Pair.js, src/core/Unit.js, src/core/flNames.js, src/core/flNames.spec.js
In response to [this issue](https://github.com/evilsoft/crocks/issues/202) we will need to have these names peppered in even more places. Makes sense to start abstracting this sooner rather than later. Eventually it will be used to invoke the function and also will be needed for comparison.
Also should clear up some of the errors when Travis runs node 6 due to the way buble was handling `@@type` before running the spec suite.
=> Move Fantasy-Land method name into one place

docs/src/pages/docs/crocks/index.md, docs/src/pages/docs/functions/pointfree-functions.md, src/core/Pair.js, src/core/Pair.spec.js
Thought I had already added `traverse` and `sequence` to both the `Pair` and `Writer` types...until I went to write an example for someone. :smh:
This PR adds those methods to `Pair` and each will traverse over the far right (second) parameter. So you can turn your `Pair Array (Maybe a)` into a `Maybe (Pair Array a)`...all the good things.
=> Add `sequence` and `traverse` to `Pair`

src/helpers/propPathOr.js, src/helpers/propPathOr.spec.js
In the previous implementation, if a property in the target is not found,
then the default value would be returned as the accumulator to the next
iteration of reduce. If the default value is an object, then it is
errantly traversed with the next property in the specified path.
=> Fix issue in propPathOr if default value is an object

src/Max/README.md
This PR addresses adding the `Max` Monoid on [this issue] (https://github.com/evilsoft/crocks/issues/42) by adding the README for `Max`
=> Add Max Documentation

src/Min/README.md
This PR addresses adding the `Min` Monoid on [this issue] (https://github.com/evilsoft/crocks/issues/42) by adding the README for `Min`
=> Add Min Documentation

docs/src/pages/docs/monoids/Prod.md, docs/src/pages/docs/monoids/Sum.md, src/Prod/README.md, src/Sum/README.md
This PR just makes a couple corrections to the `Prod` and `Sum` Monoid docs. Both the READMEs and the Docs.
=> Clean up Prod and Sum Docs

docs/src/pages/docs/functions/pointfree-functions.md, docs/src/pages/docs/monoids/Max.md, docs/src/pages/docs/monoids/Min.md, docs/src/pages/docs/monoids/index.md
These are the last (2) Docs that round out the Monoids!!
At this point all Monoids that ship with `crocks` are fully documented...
=> Add `Max` and `Min` Monoids to the docs

docs/src/pages/docs/crocks/Maybe.md, docs/src/pages/docs/functions/helpers.md, docs/src/pages/docs/functions/predicate-functions.md, src/Maybe/README.md, src/Maybe/prop.js, src/Maybe/prop.spec.js, src/Maybe/propPath.js, src/Maybe/propPath.spec.js, src/helpers/propOr.js, src/helpers/propOr.spec.js, src/helpers/propPathOr.js, src/helpers/propPathOr.spec.js, src/index.js, src/index.spec.js, src/predicates/hasProp.js, src/predicates/hasProp.spec.js, src/predicates/hasPropPath.js, src/predicates/hasPropPath.spec.js, src/predicates/propEq.js, src/predicates/propEq.spec.js, src/predicates/propPathEq.js, src/predicates/propPathEq.spec.js, src/test/LastMonoid.js, src/test/MockCrock.js
A lot of work on the last release was focused around some of the Object Traversal Functions provided by `crocks`. This forced me to look at some inconsistencies  between these functions and how `undefined` values are treated through out the library as a whole.
This PR brings them all inline and has them behave the same way across the board:
* The key/paths MUST be `(String | Integer)` or `[ String | Integer ]`. All functions will throw a `TypeError` if this condition is not met. This lets values like `null` and `undefined` to be rejected and avoid String coercion when traversing keys. A key of 'null' or 'undefined' will HAVE to be supplied to access keys of those names.
* Any traversable value/instance (except `NaN`) can be provided as the object of traversal.  Any non-traversable values …
=> All Object Traversal Functions Behave the Same

docs/src/pages/docs/crocks/Maybe.md, docs/src/pages/docs/functions/pointfree-functions.md, src/Either/Either.spec.js, src/Either/index.js, src/Identity/Identity.spec.js, src/Identity/index.js, src/Maybe/README.md, src/Result/Result.spec.js, src/Result/index.js, src/core/List.js, src/core/List.spec.js, src/core/Maybe.js, src/core/Maybe.spec.js, src/core/Pair.js, src/core/Pair.spec.js, src/core/apOrFunc.js, src/core/apOrFunc.spec.js, src/core/array.js, src/core/array.spec.js, src/pointfree/sequence.js, src/pointfree/sequence.spec.js, src/pointfree/traverse.js, src/pointfree/traverse.spec.js
This is another step in getting us Fantasy Land compliant for `fantasy-land/traverse` and `fantasy-land/ap`. This PR accepts a `crocks` based `Appicative TypeRep` or a `crocks` based `Apply` returning function as the single argument to `sequence` and the first argument to `traverse`. This is needed to account for what the FL spec calls for, but still retains the nimbleness of the `Apply` returning function.
This is the first part of [this issue](https://github.com/evilsoft/crocks/issues/233).
The reason we are locked to `crocks` based in this PR is for a couple reasons that will be addressed in subsequent PRs:
* `isApplicative` uses the `@@implements` implementation on the `TypeRep` which is not part of the FL spec. It also makes sure that `map` and `ap` are defined on instances of the …
=> Allow `sequence` and `traverse` to accept an `Applicatve TypeRep`

src/Either/Either.spec.js, src/Identity/Identity.spec.js, src/Result/Result.spec.js, src/core/List.spec.js, src/core/Maybe.spec.js, src/core/Pair.spec.js, src/core/apOrFunc.js, src/core/array.js, src/core/array.spec.js, src/core/isTypeRepOf.js, src/core/isTypeRepOf.spec.js
This PR allows using the Array 🌽structor for traverse and sequence by using a new internal helper to determine if a constructor matches a target. Well really it is checking if the name is the same. As this is an internal function, it should be just fine, as we will be providing the parameters.
This is the final bit of functionality needed to complete out [this issue](https://github.com/evilsoft/crocks/issues/233).
=> Allow Array Constructor as TypeRep for sequence and traverse

src/Assign/Assign.spec.js, src/core/inspect.js, src/core/inspect.spec.js, src/test/MockCrock.js
This PR fixes #251 by recursively calling `inspect` on object properties.
=> Make inspect method stringify objects (#251)

.travis.yml, package-lock.json, package.json, webpack.config.js
With the release of node `10.x`, we can now remove the build dep on node `4.2`. Which in turn means we can FINALLY upgrade to webpack 4. 🎉 
This means that CONTRIBUTOR node must be `6.x`+, many of the updates here will not work with anything less.
=> Time to Upgrade

src/core/hasAlg.js, src/core/hasAlg.spec.js, src/core/isAlt.spec.js, src/core/isApplicative.spec.js, src/core/isApply.spec.js, src/core/isBifunctor.spec.js, src/core/isChain.spec.js, src/core/isContravariant.spec.js, src/core/isExtend.spec.js, src/core/isFoldable.spec.js, src/core/isFunctor.spec.js, src/core/isMonad.spec.js, src/core/isMonoid.spec.js, src/core/isPlus.spec.js, src/core/isProfunctor.js, src/core/isProfunctor.spec.js, src/core/isSemigroup.spec.js, src/core/isSemigroupoid.spec.js, src/predicates/isAlternative.spec.js, src/predicates/isCategory.spec.js, src/predicates/isProfunctor.js, src/predicates/isProfunctor.spec.js, src/predicates/isSetoid.spec.js, src/predicates/isTraversable.spec.js, src/test/helpers.js
As a first step to [this issue](https://github.com/evilsoft/crocks/issues/202) we need to get the Fantasy Land Methods/Function specific predicates to respect the fantasy-land spec. This PR adds the following to all fantasy-land predicates:
* Check for method on passed object (Constructor/Instance), favoring the fantasy-land prefix over non-decorated.
* Check for method on `constructor` for methods specific to the `TypeRep`. `crocks` provides these functions on the instance as well as the `TypeRep`, but not all libs do that, so we need to check the `TypeRep` of the instance.
* Check for `@@implements` method. There are functions in crocks that can take a `TypeRep` as arguments and need to use that `TypeRep` for typeclass validation. For instance `isFunctor(Identity)` would return true. …
=> Add Fantasy Land Compliance for Associated Predicates

src/core/equals.js, src/core/equals.spec.js, src/core/hasAlg.js, src/core/isApplicative.js, src/core/isMonoid.js, src/core/isPlus.js, src/pointfree/alt.js, src/pointfree/alt.spec.js, src/pointfree/bimap.js, src/pointfree/bimap.spec.js, src/pointfree/chain.js, src/pointfree/chain.spec.js, src/pointfree/concat.js, src/pointfree/concat.spec.js, src/pointfree/contramap.js, src/pointfree/contramap.spec.js, src/pointfree/empty.js, src/pointfree/empty.spec.js, src/pointfree/extend.js, src/pointfree/extend.spec.js, src/pointfree/map.js, src/pointfree/map.spec.js, src/pointfree/promap.js, src/pointfree/promap.spec.js, src/pointfree/reduce.js, src/pointfree/reduce.spec.js, src/predicates/isCategory.js
This PR finishes off [this issue](https://github.com/evilsoft/crocks/issues/202) by adding a preference to fantasy-land methods/functions over non-decorated methods/functions.
Like with the predicates, this covers all of the methods/functions that are implemented at this time. When we add the `ap` and `traverse` implementations, we will go back and add both the assosiated predicates and pointfree functions.
Tested these against `folktale`, `Fluture`, `creed` and `most`
=> Add Fantasy Land Compliance for Pointfree Functions

docs/src/pages/docs/crocks/Pair.md, docs/src/pages/docs/crocks/Tuple.md, docs/src/pages/docs/crocks/index.md, docs/src/pages/docs/functions/pointfree-functions.md, src/Tuple/index.js, templates/ADT_doc.md
This PR is the final outstanding portion for the upcoming anticipated release and has all the Documentation changes/additions from the addition of the new `Tuple type`. For the most part, this PR does the following:
* Remove `merge` from the `Pair` portion of the docs as it is now used for both `Pair` and `Tuple`
* Update code references to `crocks/Pair/merge` in all the code examples in the docs.
* Fix a search/replace mistake from a previous PR. `(twoals -> equals)`.
* Add `Tuple` documentation.
* Add `Tuple` links to the `crocks` index page to the main article and functions.
* Add `merge` and `nmap` to the search list for the pointfree page.
* Update the path for `merge` to read the general `crocks/pointfree` on the pointfree index page
* Add links to `Tuple` pointfree targets on the …
=> Add Tuple documentation

src/core/Pair.js, src/core/Pair.spec.js
Looks like we missed one of the fantasy land methods on `Pair`.
This PR just fixes up the method so it properly applies the method name for error reporting.
=> Fix up the Fantasy Land `bimap` method on `Pair`

docs/src/pages/docs/functions/predicate-functions.md, src/index.spec.js, src/predicates/index.js, src/predicates/index.spec.js, src/predicates/propPathSatisfies.js, src/predicates/propPathSatisfies.spec.js, src/predicates/propSatisfies.js, src/predicates/propSatisfies.spec.js
Addressing the last (2) items on [this issue](https://github.com/evilsoft/crocks/issues/302), this PR add the predicate functions: `propSatisfies` and `propPathSatisfies` that allows one to check a value on an object to see if it passes a provided predicate (function or Pred Type).
=> Add `propSatisfies` and `propPathSatisfies` to the Predicates

docs/src/pages/docs/functions/helpers.md, docs/src/pages/docs/functions/index.md, src/helpers/index.js, src/helpers/index.spec.js, src/helpers/unsetPath.js, src/helpers/unsetPath.spec.js, src/index.spec.js
This PR adds a function that provides the functionality from the `dissocPath` function provided by `ramda`. This was motivated by the documentation on the [meiosis project](https://github.com/foxdonut/meiosis) from @foxdonut.
This PR signals a change to some of the existing functions to match this new naming convention for dealing with functions like: `prop` and `propPath`. The following functions will be addressed in the next breaking change release, although they will be deprecated and their original names will still be available until we hit `1.0.0`:
* `Maybe/propPath` -> `Maybe/getPath`
* `Maybe/prop` -> `Maybe/getProp`
* `helpers/assoc` -> `helpers/setProp` (will work with `Array` as well)
* `helpers/dissoc` -> `helpers/unsetProp` (will work with `Array` as well)
* `helpers/propOr` …
=> Add `unsetPath` helper function

docs/src/pages/docs/crocks/Async.md
This is for #203, I've deliberately left out examples for `asyncToPromise`. I don't see any value in it or think it would be a common thing. Happy to hear otherwise though
=> Added flattening examples to Async

src/core/List.js, src/core/List.spec.js, src/core/flNames.js, src/pointfree/filter.js, src/pointfree/filter.spec.js
This PR addresses #237 
I'm not sure if we need to change this in the pointfree docs - I see that most functions don't represent a typeclass. Thoughts?
=> Change Foldable to Filterable on List.filter for FL Compliance

docs/src/pages/docs/functions/index.md, docs/src/pages/index.soy
This PR does the following:
* Adds the `converge` link on the Functions Landing Page
* Updates the Features Links to work with `gh-pages`
=> Fixup some Links in the Docs

docs/src/pages/docs/functions/helpers.md, docs/src/pages/docs/functions/index.md, src/core/array.js, src/core/array.spec.js, src/core/object.js, src/core/object.spec.js, src/helpers/setPath.js, src/helpers/setPath.spec.js, src/helpers/setProp.js, src/helpers/unsetPath.js, src/helpers/unsetPath.spec.js
As part of this [this issue](https://github.com/evilsoft/crocks/issues/329), there are some opportunities to clean some bits up around the Path functions. This PR implements those changes by doing the following:
* Add `unset` function to `core/array`
* Add `unset function to `core/object`
* Remove a couple needless checks on keys in `setPath`
* Report key based errors in `setPath` outside of next being an Array or Object.
* update `unsetPath` to use new `unset` functions in `array` and `object`
* update `unsetPath` to report errors more like `setPath`
=> More changes to setPath and unsetPath

docs/src/pages/docs/crocks/Async.md
Update to fix the issue raised with the example in `Async`
Tested that this is now working.
I am thinking it might be worth while going through and checking all the examples in the docs, just to be sure
=> Minor update to fix docs bug

docs/src/pages/docs/functions/helpers.md, docs/src/pages/docs/functions/index.md, src/helpers/dissoc.js, src/helpers/dissoc.spec.js, src/helpers/index.js, src/helpers/unsetProp.js, src/helpers/unsetProp.spec.js, src/index.spec.js
This PR addresses part of [this issue](https://github.com/evilsoft/crocks/issues/329) and adds the `unsetProp` function while also depreciating `dissoc`. The behavior for argument handling matches `unsetPath` in that:
* Only allows non-empty `String`s and positive `Integer`s for referencing keys/indices on a given `Object`/`Array`
* Will echo the provided target when it is not an `Object` or `Array`
=> Add `unsetProp` and deprecate `dissoc` in favor of the new function

.eslintignore, docs/src/pages/docs/functions/combinators.md
This PR is to complete the issue https://github.com/evilsoft/crocks/issues/380
I am going to be working on each piece however if anyone reviews and approves, i'm happy to merge with some of the items complete
=> Updating descriptions and adding examples for combinators

package.json
Looks like when upgrading we broke the build stack for node 6 testing due to how uglifyjs handles unrecognized options. This is cause a build failure for the node 6 stacks. This PR should resolve the failed builds.
=> Remove `warning` option for uglifyjs to fix node 6 builds

src/Either/Either.spec.js, src/Either/index.js
Introduced in release 0.9.4 with commit https://github.com/evilsoft/crocks/commit/6bc5377cf4a47a927ff3fa407073d17aa3b0cdbe#diff-d70a7c87b679a4d796e121bd30e12fd1 the `inspect` function recursively stringifies objects which will blow the callstack when given an object containing a circular reference.
This bug is triggered when constructing an Either due to its `inspect` method being eagerly evaluated during construction.
=> Fix Either constructor when called with object containing a circular reference

.travis.yml
What it says on the tin. We only support the last three LTS versions. This drops 6 and adds 12.
=> Update CI to remove node-6 and add node-12

docs/src/pages/docs/functions/predicate-functions.md, src/index.spec.js, src/predicates/hasProps.js, src/predicates/hasProps.spec.js, src/predicates/index.js, src/predicates/index.spec.js
This will allow us to pass an array of keys instead of a single key to check the structure of an object.
Have some things to point out
1. Are we ok with the use of `every`? I'm not married to it and am happy to convert it to reduce
2. Right now it doesn't support taking either the Array or the single value, do we want to do that?
3. Is that the correct way to specify the expected values in an Array? I see that everywhere else we're using just Array but it'd be nice to be more specific in the signature
=> Adding new `hasProps` predicate

docs/src/CNAME
Took a few to find out how to get the CNAME to publish with the docs. Tracked it down and submitting this for the next release.
=> Add CNAME to docs on Publish

src/Pair/writerToPair.spec.js, src/Writer/Writer.spec.js, src/Writer/index.js
This PR is a direct answer to implementing the breaking change as defined in [this issue][issue]. Before this change we provided the value to be wrapped in the `Monoid` and the `Writer` would wrap it for us. This created issues when dealing with empty values on types like `Array` or other structure-ish type Monoids.
Going forward, each log entry will now have to provide an instance of the `Monoid`
```js
const MaxWriter =
Writer(Max)
const oldWay =
MaxWriter(34, 'string')
const newWay =
MaxWriter(Max(34), 'string')
```
[issue]: https://github.com/evilsoft/crocks/issues/201
=> Require Monoid Instance for Log Entry When Constructing A Writer

docs/src/pages/docs/crocks/Async.md, docs/src/pages/docs/crocks/Either.md, docs/src/pages/docs/crocks/Maybe.md, docs/src/pages/docs/crocks/Result.md, docs/src/pages/docs/crocks/index.md, docs/src/pages/docs/functions/pointfree-functions.md, src/Async/Async.spec.js, src/Either/Either.spec.js, src/Either/index.js, src/Result/Result.spec.js, src/Result/index.js, src/core/Maybe.js, src/core/Maybe.spec.js, src/core/isBichain.spec.js, src/pointfree/bichain.js, src/pointfree/bichain.spec.js
This PR responds to [this issue][issue] and adds `bichain` to the remaining (3) Sum Types as it was already added on to `Async` on [this PR][pr]:
* `Either`
* `Maybe`
* `Result`
For each example in the documentation, we show both just a simple function to swap between "left"/"right" instances and a more in depth example. The exception to this is `Maybe`, which only shows the simple swap example. This is because, there is not really a solid use case that is not better implement with `alt`. Although, if anyone has any suggested, real-world use cases for the `Maybe` example, I am all :ear: 
[issue]: https://github.com/evilsoft/crocks/issues/393
[pr]: https://github.com/evilsoft/crocks/pull/394
=> Add `bichain` to remaining Sum Types

docs/src/pages/docs/crocks/Arrow.md
In the docs the property num had the same type as the example above.
The change makes clear the contramap is not working on a different property either instead of the type
=> Update example in contramap on Arrow

README.md
=> Fix two function signatures in README

docs/src/pages/docs/crocks/Either.md
In case of a Left the object is added as the value of error instead of the value of the property 'a' transferred to 'error'
=> doc(either): update setPassed example in Left either function

LICENSE
The title is not legally mandated, but it's convenient for human consumption, and is typically included in the template text of this license, as recommended by [OSI](https://opensource.org/licenses/isc-license), [SPDX](https://spdx.org/licenses/ISC.html#licenseText), [choosealicense.com](https://choosealicense.com/licenses/isc/), and others.
***Note**: This PR is part of my personal project to improve the consistency and visibility of the ISC license in open source projects. See https://github.com/github/choosealicense.com/issues/377 for more details.*"
=> Add title to LICENSE file

docs/src/pages/docs/functions/helpers.md
It was brought to my attention [on twitter][twitter] that there was a patronizing tone in the documentation for `compose` that was not very inclusive . After it was reported and I read through it, I determined that it was indeed needlessly "shaming" and being overly patronizing to a person on their preference to use `pipe` over `compose` and needed to be altered.
This PR replaces the paragraph for `compose` to just provide information on the relationship between the two. Removing the non-inclusive, shamming voice from what should be a more neutral tone. I also added some similar examples for both `pipe` and `compose` while I was in there.
[twitter]: https://twitter.com/jplinnell/status/1232621332841582592
=> Remove patronizing tone from documentation

.travis.yml, package-lock.json, package.json
Just a simple PR to get our dev stack up to date and remove a vulnerability. The updates to `husky`, `lint-staged` and `sinon` removed support for node:8, so it makes sense to move on and only test against versions `10` and `12` of node. node:8` is coming to an end on its life cycle anyway.
This should clear up the dependabot vulnerability when merged.
=> Update Deps and Remove Dev Support for Node:8

.all-contributorsrc, README.md, docs/src/pages/docs/crocks/Async.md, src/Async/Async.spec.js, src/Async/index.js
This is a first-pass at allowing the function passed to `Async.fromPromise` to be partially applied by the caller.
One of the reasons I can think for not allowing this is that `fromPromise` can always be wrapped in a function that takes additional parameters and allows `fromPromise` to handle the final parameter passed. This is what I've been doing so far for example:
```
const updateRecord = (id, body) =>
Async.fromPromise(companyId =>
db.collection(`entities/${companyId}/foo`).doc(id).update(body)
);
```
The motivation behind this addition is to provide a more natural feeling API where functions passed to crocks operations are curried by default.
With this change the code above would look like:
```
const updateRecord =
Async.fromPromise((id, body, companyId) => …
```
=> Allow fn passed to Async.fromPromise to be partially applied

src/core/curry.js, src/core/curry.spec.js
While working through a first-pass on what `Async.fromNode` might look like with its incoming parameter curried (see #478), I noticed that I was unable to check for a length on incoming curried functions.
With this change in place the code for allowing curried functions with `Async.fromNode` passes the tests.
What do you think about this change to `curry` where we expose the length on `curried` of the original `fn` that was passed in?
=> Expose a length property for curried functions

docs/src/pages/docs/crocks/Identity.md
Identity(42)
.valueOf()
//=> 42 (Must be 42) not 33
Remove following lines
Identity(20)
.concat(Identity(22))
.valueOf()
//=> 35
due to this error message. Throwing error "TypeError: Identity.concat: Both containers must contain Semigroups of the same type"
=> Output result not correct
