evilsoft/crocks

- docs/crocks/Maybe.md
> Adds Maybe API

- README.md
- transforms/arrayToList.js
- transforms/arrayToList.spec.js
- transforms/listToArray.js
- transforms/listToArray.spec.js
- transforms/maybeToEither.js
Shorted out previous #63 PR, here are review changes:
This pr will result in the following task list of issue #61:
> Adds Array <-> List transforms

- docs/IO.md
`ho io io io io io`
https://www.youtube.com/watch?v=yHbvcln1arg
> Adds IO API

- README.md
- crocks/List.js
- crocks/List.spec.js
- helpers/pipe.js
- pointfree/filter.js
- pointfree/reject.js
- pointfree/reject.spec.js
This PR is in resopnse to [Issue#55](https://github.com/evilsoft/crocks/issues/55).
It adds the `reject` function to `List` and the `reject` pointfree function.
Also some cleanup on dat README.
> Add `reject` to `List` and `reject` pointfree

- docs/crocks/List.md
> Adds List API

- docs/crocks/Arrow.md
- docs/crocks/List.md
- docs/crocks/Pred.md
> Arrow api, fixes Pred.concat

- docs/crocks/Result.md
This PR adds another skeleton to the docs for this [issue#42](https://github.com/evilsoft/crocks/issues/42). This one for the newly added `Result`.
> Add Result Skeleton

- README.md
Just an attempt at making things a little easier to follow while the docs are being built
> Add better links, heading and signatures to functions/sections on Readme

- crocks/Async.js
- crocks/Async.spec.js
With the submission of [PR#122](https://github.com/evilsoft/crocks/pull/122) which provides a pointfree `fork` function, it makes sense for `fork` to now return something. Even though the typical use case of the function would be to wrap the `fork` in a `tap` function, there may be times (like at the end of a composition) where the user would want is returned from `fork`.
At the suggestion of @gabejohnson it would make sense for a cancel function to be returned. This function can be called to cancel any pending chained `Async`s and not run them. Also when called, the `reject` and `resolve` functions passed to `fork` will never be called.
In addition to this cancel function being added, the ability to provide `onCancel` functions at the `Async` and `fork` levels. This modifies the …
> add cancellation to Async

- README.md
- src/helpers/propOr.js
- src/helpers/propOr.spec.js
- src/helpers/propPathOr.js
- src/helpers/propPathOr.spec.js
PR for #157 
Looking at the code, and noticed that `Maybe` has the `option` method, so the `propOr` should not need, but yeah, here is the PR :)
> Add `propOr` and `propPathOr` and Documentation for both

- package.json
- src/Either/index.js
- src/core/innerConcat.spec.js
Needed to update these deps for quite some time now.
> Update Development Dependencies

- CONTRIBUTORS.md
- bin/setup
- docs/electric.config.js
- docs/package.json
- docs/src/layouts/guide.soy
- package-lock.json
- package.json
Reworked the docs build system in the following:
* changed code theme to 'blackboard'
* made `dev` env for base paths for assets
* Added some fun little script runners
* 🔧 the contribute link
* added a `setup` script for dependency management.
* also lets go with npm locks, why not?
> Some small tweaks to the build system for the Docs

- docs/src/pages/index.soy
Short PR
- Changes to intent.
- Fixes Grammar & Spelling issues
- (tries to) set 🌽 sistency with playful tone through rest of docs
> Writing changes to docs index

- docs/src/pages/docs/crocks/Maybe.md
- docs/src/pages/docs/crocks/index.md
- docs/src/pages/docs/functions/helpers.md
- docs/src/pages/docs/functions/index.md
- docs/src/pages/docs/functions/pointfree-functions.md
- docs/src/pages/docs/functions/transformation-functions.md
- docs/src/pages/docs/monoids/Endo.md
- docs/src/pages/docs/monoids/index.md
This PR adds the recently merged documentation into the git pages portion of the documentation.
> Add `Endo` and `Maybe` to the documentation

- docs/src/pages/index.soy
> Fixed a typo

- src/All/All.spec.js
- src/All/index.js
- src/Any/Any.spec.js
- src/Any/index.js
- src/Assign/Assign.spec.js
- src/Assign/index.js
- src/First/First.spec.js
- src/First/index.js
- src/Last/Last.spec.js
- src/Last/index.js
- src/Max/Max.spec.js
- src/Max/index.js
- src/Min/Min.spec.js
- src/Min/index.js
- src/Prod/Prod.spec.js
- src/Prod/index.js
- src/Sum/Sum.spec.js
- src/Sum/index.js
#259 has been opened for documenting this feature.
> Add equals to most Monoids (without docs) (#230) 

- docs/src/pages/docs/crocks/Pair.md
- docs/src/pages/docs/crocks/index.md
- docs/src/pages/docs/functions/helpers.md
- docs/src/pages/docs/functions/index.md
- docs/src/pages/docs/functions/pointfree-functions.md
This PR provides the documentation (and all the links to other documents) surrounding the Pair Crock.
This is another PR that addresses the large [documentation issue](https://github.com/evilsoft/crocks/issues/42)
> Add Pair Documentation

- docs/src/pages/docs/crocks/Async.md
When resultToAsync takes function it returns function that returns Async
> update Async documentation

- src/Tuple/nmap.js
- src/Tuple/nmap.spec.js
> Make nmap work with Tuples greater than size 10

- docs/src/pages/docs/functions/index.md
- docs/src/pages/docs/functions/logic-functions.md
- src/index.spec.js
- src/logic/implies.js
- src/logic/implies.spec.js
- src/logic/index.js
This addresses the first item from [this issue](https://github.com/evilsoft/crocks/issues/302) and adds the `implies` logic combinator and its documentation.
> Add `implies` Logic Combinator

- docs/src/pages/docs/functions/predicate-functions.md
- src/core/isIterable.js
- src/core/isIterable.spec.js
- src/predicates/isIterable.js
- src/predicates/isIterable.spec.js
This is a PR to add an `isIterable` predicate in preparation for work on #29
This is something we'll obviously need internally, however I am unsure on the value of adding this as something that is part of the api, thoughts?
> Added an isIterable predicate

- docs/src/pages/docs/crocks/Maybe.md
Adding in the examples per #203
> Added flattening examples to the Maybe docs

- docs/src/pages/index.soy
- docs/src/styles/custom/_landing.scss
This is to add improvements per #208
> Updates to the layout, design and wording of the main docs page

- docs/src/pages/docs/crocks/Either.md
- docs/src/pages/docs/crocks/Pair.md
This is for adding flattening examples for `Either`, `Pair` for #203
> Added flattening examples

- docs/src/pages/docs/functions/logic-functions.md
Added examples for And. LMK if this works
> Adding examples for the `And` function

- .eslintignore
- docs/src/pages/docs/functions/logic-functions.md
This PR is to add the examples for the final four logic functions. As requested from https://github.com/evilsoft/crocks/issues/304
> Added documentation for final logic functions

- docs/src/pages/docs/crocks/Result.md
> Minor spelling mistake

- docs/src/pages/docs/crocks/Identity.md
To address, https://github.com/evilsoft/crocks/issues/423, wrapping the raw applied value into an `Identity`
Had a quick look, did not see any other obv errors
> Updating `ap` example on `Identity`

- docs/src/pages/docs/crocks/Pair.md
- docs/src/pages/docs/functions/helpers.md
- docs/src/pages/docs/functions/index.md
- src/Pair/toPairs.js
- src/Pair/toPairs.spec.js
For merging into 0.13
This work is to start the journey to complete https://github.com/evilsoft/crocks/issues/336
i'm unsure if the type sig for arr is `[ String ]` or `Array String`
> Changing toPairs to return an array

- package-lock.json
- package.json
Did some minor (and one major) updates on the DevDeps to clear up all dat `lodash` noise.
Got some minor optimizations on some of the build process.
> Clear up Security :corn:cerns

- src/core/curry.js
- src/core/curry.spec.js
- src/helpers/unary.js
adding in a propery to check if the passed in function has already been run through our curry method
> Micro-optimization to curry

- package-lock.json
- package.json
Just a some update to outdated, non-breaking packages. This will clear up a potential vulnerability in our deps (for library devs, not for library users)
> Update Dev Deps For Security

- CODINGSTANDARDS.md
- CONTRIBUTING.md
- src/Maybe/find.js
- src/Maybe/find.spec.js
The purpose of this PR is to close out this issue, https://github.com/evilsoft/crocks/issues/88
> Adding in CONTRIBUTING and CODINGSTANDARDS

- package-lock.json
- package.json
Noticed we are a little out of date on a few development dependencies. This PR just upgrades them all in anticipation for an upcoming release.
We have not fully upgraded `tape` to the `5.0.0` version yet, we will need to work on redoing all `plan` based specs for that. BUT they are maintaining `4.x`, so that is super awesome!
> Upgrade all the things

- docs/src/pages/docs/crocks/Pair.md
- docs/src/pages/docs/crocks/Writer.md
Long overdue PR, very happy to strike this off my to do list! Please take a look guys.
> Add Writer docs, minor corrections to Pair docs

- docs/src/pages/docs/crocks/Pair.md
Update import path from 'crocks/Pair/merge' to 'crocks/pointfree/merge'.
> Small Change

- package-lock.json
- package.json
> Upgrading packaged to remove vulnerability in Lodash and bringing some up to date
